global:
  scrape_interval: 10s

scrape_configs:
  - job_name: open5gs-amfd
    static_configs:
      - targets: 
        - '10.220.2.106:9093'
  - job_name: open5gs-pcfd
    static_configs:
      - targets:
        - '10.220.2.106:9092'
  - job_name: open5gs-smfd
    static_configs:
      - targets:
        - '10.220.2.106:9094'
  - job_name: open5gs-upfd
    static_configs:
      - targets:
        - '10.220.2.106:9091'