logger:
    file:
      path: /open5gs/install/var/log/open5gs/ausf.log
    level: debug

global:

ausf:
  sbi:
    server:
      - address: ausf.open5gs.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.open5gs.org:80