logger:
    file:
      path: /open5gs/install/var/log/open5gs/udm.log
    level: debug

global:

udm:
  sbi:
    server:
      - address: udm.open5gs.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.open5gs.org:80
